[package]
name = "rts"
version = "0.1.0"
authors = ["Jeffrey C. Ollie <jeff@ocjtech.us>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scoped_threadpool = "0.1.*"
chrono = "0.4"
